<?php
// Call the CMS System
$CT = new CMS(
    [
        "lg"=>"de",
        "legend"=>true,
        "back_days"=>true,
        "tooltip"=>true,
        "events_check"=>true,
        "hidden_months"=>'3',
        "static_infos"=>[
            'active'=>true,
            'events'=>true,
            'version'=>true,
            'language'=>true
        ],
        "event_form"=>[
            'active'=>true,
            'action'=>'?page_2',
            'person_check'=>true,
            'payment_check'=>true,
            'active_event'=>'2'
        ],
        "min_year"=>'2000',
        "max_year"=>'2030',
        "theme"=>'Horizon',
        "buttons"=>[
            'active'=>true,
            "prev_year"=>true,
            "next_year"=>true,
            "prev_month"=>true,
            "next_month"=>true,
            "today"=>true,
        ]
    ]
);
?>