<?php
// Call the CMS System
$CT = new CMS(
    [
        "lg"=>"de",
        "back_days"=>true,
        "tooltip"=>true,
        "events_check"=>true,
        "hidden_months"=>'3',
        "static_infos"=>[
            'active'=>true,
            'events'=>true,
            'version'=>true,
            'language'=>true
        ],
        "event_form"=>[
            'active'=>true,
            'action'=>'?page_2',
            'person'=>true,
            'payment'=>true,
            'active_event'=>'2'
        ],
        "min_year"=>'2000',
        "max_year"=>'2030',
        "theme"=>[
            "theme"=>'Horizon'
        ],
        "header"=>[
            "left"=>[
                "legend"
            ],
            "center"=>[
                "prev_year",
                "next_year",
                "prev_month",
                "next_month",
                "today",
            ]
        ]
    ]
);
?>