<?php
// Call the CMS System
$CT = new CMS(
    [
        "tooltip"=>true,
        "events_check"=>true,
        "header"=>[
            "left"=>[
                "legend"
            ],
            "center"=>[
                "prev_year",
                "next_year"
            ],
            "right"=>[
                "week_view",
                "year_view",
                "day_view"
            ]
        ],
        "theme"=>[
            "theme"=>'Horizon',
        ],
        "time_format"=>'H.i',
        "database_check"=>false,
        "error_log"=>true,
        "cur_year"=>'2019',
        "my_events"=>[
            [
                "event_name"=>"Test",
                "start_date"=>"2019-12-16",
                "end_date"=>"2019-12-26",
                "my_description"=>"Test array 1",
                "test_event"=>"0",
                "event_code"=>"meoghetnghgwtb",
                "email"=>"info@test.de",
                "firstname"=>"Florian",
                "lastname"=>"Lämmlein"
            ],
            [
                "event_name"=>"Test_2",
                "start_date"=>"2019-12-03",
                "end_date"=>"2019-12-12",
                "my_description"=>"Test array 2",
                "test_event"=>"0",
                "event_code"=>"gkrgmoejmohreh",
                "email"=>"info@test.de",
                "firstname"=>"Max",
                "lastname"=>"Mustermann"
            ]
        ],
        "date_format"=>"d.m.Y",
        "event_form"=>[
            'active'=>true
        ],
        "static_infos"=>[
                "active"=>true,
                "events"=>true,
                "version"=>true,
                "authors"=>true,
                "language"=>true,
                "theme"=>true
            ]
    ]
);
?>